services:
  app:
    build: 
      context: .
      dockerfile: dockerfile
      args:
        - BUILD_VERSION=DEV
    platform: linux/amd64
    volumes:
      - ../..:/Projects

    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:password@db:27017/
      
  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongodb:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@db:27017/
      ME_CONFIG_BASICAUTH: false